### ISSUE TITLE
User management and Authentication for Local users in Database

### ISSUE THREAD

**Issue by rx294** [mitre/heimdallts#2]
In phase 1, HS2 will use local users specified in the internal db.
- [x] Autogenerate random initial password for root user and print to screen and to install log // Do not autogenerate password if root password already set in db ( allowing scaling )
- [x] Implement password reset functionality for users (API)
- [x] On initial root user login force password reset (api) // Do not force password reset if root password already set in db ( allowing scaling )
- [ ] password reset components and flow through (UI)
- [x] Implement password strength reqs in backend
- [x] Implement simple role-based permission system to have an application root user
- [x] Root user can Update and destroy users (API and backend validation)
- [x] Root user can force password reset for users (API and backend validation)
- [ ] Component(s) for the root user to view, update, and destroy users (UI)
- [ ] Component for the root user to reset users password
- [x] User attrs: fname, lname, email, title, org 
- [ ] Login users though UI
- [ ] Signup users through UI
- [ ] Profile page (UI)
- [x] Refactor Signup through API
- [x] Refactor Login through API
- [x] Room for expansion of user attrs useful later : 2fa, access type, UI 
preferences
- [x] Backend validate password complexity requirements for update and create.

**Comment by Bialogs** [comment]
Closing this as the API tasks are done and I've moved over the "(UI)" tasks to the heimdall-lite issue tracker.
