### ISSUE TITLE
Unit and functional Test Phase 1 features

### ISSUE THREAD

**Issue by rx294** [mitre/heimdallts#7]
- [x] Password match pipe unit tests
- [x] Password change pipe unit tests
- [x] Password complexity pipe unit tests
- [x] Users service unit tests
- [x] Users controller unit tests
- [x] End to end test for user update (all attributes including password/admin and not admin)

**Comment by samuelsunvold** [comment]
Worked on unit tests for users.service and have finished a couple tests so far

**Comment by rx294** [comment]
Users service unit tests
 Users controller unit tests
https://github.com/Bialogs/heimdall2/pull/8

**Comment by samuelsunvold** [comment]
Password complexity pipe unit tests (Most tests are done, but not 100% done yet)
https://github.com/Bialogs/heimdall2/pull/12

**Comment by samuelsunvold** [comment]
E2E(integration/controller) tests
https://github.com/Bialogs/heimdall2/pull/16
